version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang:1.12
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run: go vet -v ./...
    - run: go test -v ./...
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
  build:
    docker:
    - image: circleci/golang:1.12
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run: go install github.com/mitchellh/gox
    - run: 
        name: "Build (amd64)"
        command: |
          VER=$(git describe --tags)
          gox -ldflags="-X 'github.com/screepers/screeps-launcher/v1/version.BuildTime=$(date)' -X 'github.com/screepers/screeps-launcher/v1/version.BuildVersion=${VER}'" -os="linux darwin windows" -arch="amd64" -output="dist/screeps-launcher_${VER}_{{.OS}}_{{.Arch}}" ./cmd/screeps-launcher/
    - run: 
        name: "Build (arm,arm64)"
        command: |
          VER=$(git describe --tags)
          gox -ldflags="-X 'github.com/screepers/screeps-launcher/v1/version.BuildTime=$(date)' -X 'github.com/screepers/screeps-launcher/v1/version.BuildVersion=${VER}'" -os="linux" -arch="arm arm64" -output="dist/screeps-launcher_${VER}_{{.OS}}_{{.Arch}}" ./cmd/screeps-launcher/
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
    - store_artifacts:
        path: config.sample.yml
        destination: config.sample.yml
    - store_artifacts:
        path: dist
        destination: ''
    - persist_to_workspace:
        root: dist
        paths:
        - '*'
  build-docker:
    docker:
    - image: docker:18.09
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build Image
        command: docker build -t $CIRCLE_PROJECT_REPONAME .
    - run:
        name: Tag Image
        command: |
          set -x
          DOCKER_IMAGE=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:${CIRCLE_SHA1:0:7}
          if [[ -n "$CIRCLE_BRANCH" ]]; then
            docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:$CIRCLE_BRANCH
          fi
          if [[ -n "$CIRCLE_TAG" ]]; then
            docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:$CIRCLE_TAG || true
            docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:latest || true
          fi
    - run:
        name: Push to Repo
        command: |
          DOCKER_IMAGE=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_IMAGE
  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: "Publish Release on GitHub"
        command: |
          VERSION=${CIRCLE_TAG}
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
    - test:
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - build:
        requires:
        - test
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - build-docker:
        requires:
        - test
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v[0-9.]+$/
