version: '3'
services:
  main:
    build: './main'
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: devpassword
    ports:
    - 8000:8000
    volumes:
    - ..:/workspace
    - ~/.ssh:/root/.ssh-localhost:ro
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
    - 8080:80